[package]
name = "waysted"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
chrono.workspace = true
regex.workspace = true
waysted-core = { path = "../core" }
serde_json.workspace = true
