[package]
name = "waysted-core"
version = "0.1.0"
edition = "2024"

[dependencies]
niri-ipc.workspace = true
log.workspace = true
rusqlite.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
